### ISSUE TITLE
add "visually hidden" mixin/helper

### ISSUE THREAD

**Issue by callmecavs** [callmecavs/outset#23]
add a class or Sass mixin to hide something in a manner that is still accessible to screen readers

[html5bp](https://github.com/h5bp/html5-boilerplate/blob/master/dist/css/main.css#L113-L133) uses:

```css
.sr-only {
  border: 0;
  clip: rect(0, 0, 0, 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  white-space: nowrap;
  width: 1px;
}
```
